import { useMemo, useState } from "react";
import { departments, useApp } from "../data/store";
import { exportWorkbook } from "../lib/excel";
import { Badge, Button, Card, DateField, Input, MonthField, PageHeader, Select } from "../components/ui";

export function RawAttendancePage() {
  const { scopedRaw } = useApp();
  const raw = scopedRaw();
  const [q, setQ] = useState(""); const [dept, setDept] = useState("all"); const [mode, setMode] = useState<"day"|"month"|"year">("day");
  const dates=[...new Set(raw.map(r=>r.date))].sort(); const [date,setDate]=useState(dates[dates.length-1]??"2026-09-24"); const [month,setMonth]=useState((date||"2026-09").slice(0,7)); const [year,setYear]=useState((date||"2026").slice(0,4));
  const rows=useMemo(()=>raw.filter(r=>`${r.name} ${r.personId} ${r.department} ${r.status}`.toLowerCase().includes(q.toLowerCase().trim())&&(dept==="all"||r.department===dept)&& (mode==="day"?r.date===date:mode==="month"?r.date.startsWith(month):r.date.startsWith(year))),[raw,q,dept,mode,date,month,year]);
  const exportRows=rows.map(r=>({No:r.no,"Person ID":r.personId,Name:r.name,Department:r.department,Position:r.position,Gender:r.gender,Date:r.date,Week:r.week,Timetable:r.timetable,"Check-in":r.checkIn,"Check-out":r.checkOut,Work:r.work,OT:r.ot,Attended:r.attended,Late:r.late,Early:r.early,Absent:r.absent,Leave:r.leave,Status:r.status,Records:r.records,Batch:r.batchId}));
  return <div><PageHeader title="Raw attendance" subtitle="Review the exact fingerprint-device rows, filter them by employee, department and modern calendar period, then export a daily, monthly or yearly extract." actions={<div className="flex flex-wrap gap-2"><Button onClick={()=>exportWorkbook(`RICA_raw_${mode}_${mode==='day'?date:mode==='month'?month:year}.xlsx`,exportRows)}>Export {mode}</Button></div>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input placeholder="Search employee name, ID, department…" value={q} onChange={e=>setQ(e.target.value)}/><Select value={dept} onChange={e=>setDept(e.target.value)}><option value="all">All departments</option>{[...new Set(raw.map(r=>r.department))].sort().map(d=><option key={d}>{d}</option>)}</Select><Select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="day">Daily export</option><option value="month">Monthly export</option><option value="year">Yearly export</option></Select>{mode==='day'?<DateField label="Date" value={date} onChange={setDate}/>:mode==='month'?<MonthField label="Month" value={month} onChange={setMonth}/>:<Input aria-label="Year" type="number" min="2000" max="2100" value={year} onChange={e=>setYear(e.target.value)}/>}</div>
    <Card className="overflow-auto"><table className="min-w-[1450px] w-full text-left text-xs"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr>{["No.","Person ID","Name","Department","Position","Gender","Date","Week","Timetable","Check-in","Check-out","Work","OT","Attended","Late","Early","Absent","Leave","Status","Records","Batch"].map(h=><th key={h} className="whitespace-nowrap px-3 py-2">{h}</th>)}</tr></thead><tbody>{rows.slice(0,500).map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-3 py-2">{r.no}</td><td className="px-3 py-2 font-mono">{r.personId}</td><td className="px-3 py-2 font-medium">{r.name}</td><td className="px-3 py-2">{r.department}</td><td className="px-3 py-2">{r.position}</td><td className="px-3 py-2">{r.gender}</td><td className="px-3 py-2">{r.date}</td><td className="px-3 py-2">{r.week}</td><td className="px-3 py-2">{r.timetable}</td><td className="px-3 py-2">{r.checkIn||"—"}</td><td className="px-3 py-2">{r.checkOut||"—"}</td><td className="px-3 py-2">{r.work}</td><td className="px-3 py-2">{r.ot}</td><td className="px-3 py-2">{r.attended}</td><td className="px-3 py-2">{r.late}</td><td className="px-3 py-2">{r.early}</td><td className="px-3 py-2">{r.absent}</td><td className="px-3 py-2">{r.leave}</td><td className="px-3 py-2"><Badge tone={r.status==='Absent'?'rose':r.status==='LV'?'sky':'teal'}>{r.status}</Badge></td><td className="px-3 py-2 font-mono">{r.records}</td><td className="px-3 py-2">{r.batchId}</td></tr>)}{rows.length===0&&<tr><td colSpan={21} className="px-4 py-10 text-center text-slate-500">No raw attendance records match the filters.</td></tr>}</tbody></table></Card><p className="mt-2 text-xs text-slate-400">Showing {Math.min(500,rows.length)} of {rows.length} matching rows.</p></div>;
}
