import { useMemo, useState } from "react";
import { UploadCloud, FileSpreadsheet, CheckCircle2, AlertTriangle, Link as LinkIcon } from "lucide-react";
import { downloadImportTemplate, parseRawWorkbook } from "../lib/excel";
import { RAW_HEADERS } from "../lib/utils";
import { useApp } from "../data/store";
import { Badge, Button, Card, PageHeader } from "../components/ui";
import { can } from "../lib/permissions";
import type { AttendanceRaw } from "../types";

export function UploadPage() {
  const { currentUser, importRaw, batches } = useApp(); const allowed=currentUser&&can(currentUser.role,"upload");
  const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState<AttendanceRaw[]>([]); const [fileName,setFileName]=useState(""); const [url,setUrl]=useState("");
  async function selectFile(file:File){ setError("");setStatus("");setBusy(true);try{const rows=parseRawWorkbook(await file.arrayBuffer(),"preview");setPreview(rows);setFileName(file.name);}catch(e){setPreview([]);setError(e instanceof Error?e.message:"Failed to parse workbook.");}finally{setBusy(false);} }
  async function loadUrl(){
    if(!url.trim()) return; setError(""); setStatus(""); setBusy(true);
    try { const response=await fetch(url.trim()); if(!response.ok) throw new Error(`Unable to fetch file (HTTP ${response.status}). The server may block browser access.`); const buffer=await response.arrayBuffer(); const rows=parseRawWorkbook(buffer,"url"); setPreview(rows); setFileName(url.split("/").pop() || "remote-attendance.xlsx"); }
    catch(e){ setPreview([]); setError(e instanceof Error ? `${e.message} If the source blocks CORS, download the Excel file and use Select file.` : "Unable to load the URL."); }
    finally { setBusy(false); }
  }
  function commit(){if(!preview.length)return;const result=importRaw(preview,fileName);setStatus(`Imported ${fileName}: ${preview.length} parsed, ${result.duplicates} duplicates skipped, ${result.anomalies} anomalies flagged. Batch ${result.batchId}.`);setPreview([]);setFileName("");}
  const expected=useMemo(()=>RAW_HEADERS.join(" · "),[]);
  if(!allowed)return <Card className="p-8"><h1 className="text-lg font-semibold">Upload restricted</h1><p className="mt-2 text-sm text-slate-500">Only Admin can import fingerprint device exports.</p></Card>;
  return <div><PageHeader title="Data import" subtitle="Select an .xls/.xlsx device export, preview exactly what will be imported, then confirm the import." />
    <div className="grid gap-6 lg:grid-cols-3"><Card className="p-6 lg:col-span-2"><label className="flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50/40 px-6 py-12 text-center hover:bg-teal-50"><UploadCloud className="text-teal-700"/><p className="mt-3 font-semibold">{fileName||"Select Excel file"}</p><p className="mt-1 text-xs text-slate-500">The file is parsed locally first. Nothing is imported until you confirm.</p><input type="file" accept=".xls,.xlsx" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void selectFile(f)}}/><div className="mt-4 flex flex-wrap justify-center gap-2"><Button type="button" disabled={busy}>{busy?"Reading file…":"Select file"}</Button><Button type="button" variant="secondary" onClick={e=>{e.preventDefault();downloadImportTemplate()}}>Download template</Button></div></label>
      <div className="mt-4 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><LinkIcon size={17} className="text-teal-700"/><h3 className="font-semibold">Import from URL</h3></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/attendance.xlsx" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-4 focus:ring-teal-600/20"/><Button type="button" onClick={()=>void loadUrl()} disabled={busy}>{busy?"Loading…":"Load URL"}</Button></div><p className="mt-2 text-xs text-slate-500">The remote server must allow browser access (CORS). Otherwise download the workbook and select it above.</p></div>
      {status&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{status}</p>}{error&&<p className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
      {preview.length>0&&<div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Import preview</h2><p className="text-xs text-slate-500">{preview.length} rows parsed successfully from {fileName}.</p></div><Button onClick={commit}>Confirm import</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-xs text-slate-500">Rows ready</p><p className="text-2xl font-bold">{preview.length}</p></Card><Card className="p-4"><p className="text-xs text-slate-500">Unique employees</p><p className="text-2xl font-bold">{new Set(preview.map(r=>r.personId)).size}</p></Card><Card className="p-4"><p className="text-xs text-slate-500">Date range</p><p className="text-sm font-bold">{preview.map(r=>r.date).sort()[0]} → {preview.map(r=>r.date).sort().at(-1)}</p></Card></div><div className="mt-4 overflow-auto rounded-xl border border-slate-100"><table className="min-w-[900px] w-full text-left text-xs"><thead className="bg-slate-50"><tr>{["Person ID","Name","Department","Date","Check-in","Check-out","Status"].map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{preview.slice(0,12).map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-3 py-2 font-mono">{r.personId}</td><td className="px-3 py-2">{r.name}</td><td className="px-3 py-2">{r.department}</td><td className="px-3 py-2">{r.date}</td><td className="px-3 py-2">{r.checkIn||"—"}</td><td className="px-3 py-2">{r.checkOut||"—"}</td><td className="px-3 py-2">{r.status}</td></tr>)}</tbody></table></div><p className="mt-2 text-xs text-slate-400">Previewing first {Math.min(12,preview.length)} rows. All {preview.length} rows will be imported after confirmation.</p></div>}
      <div className="mt-6"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Required columns</p><p className="mt-2 text-xs leading-6 text-slate-600">{expected}</p></div></Card>
      <Card className="p-6"><div className="flex items-center gap-2"><FileSpreadsheet size={18} className="text-teal-700"/><h2 className="font-semibold">Import batches</h2></div><p className="mt-1 text-xs text-slate-500">Every confirmed import receives a unique Batch ID and anomaly count.</p><ul className="mt-4 space-y-3">{batches.map(b=><li key={b.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{b.id}</p><Badge tone={b.status==='Verified'?'emerald':b.status==='Imported'?'sky':'amber'}>{b.status}</Badge></div><p className="mt-1 truncate text-xs text-slate-500">{b.fileName}</p><p className="mt-1 text-xs text-slate-500">{b.rowCount} rows · {b.duplicates} duplicates · {b.anomalies} anomalies</p><div className="mt-2 flex items-center gap-1 text-[11px] text-slate-500"><CheckCircle2 size={13}/> Imported and stored</div>{b.anomalies>0&&<div className="mt-1 flex items-center gap-1 text-[11px] text-amber-700"><AlertTriangle size={13}/> Review anomalies</div>}</li>)}</ul></Card></div></div>;
}
